"""Add Project and ApiKey models

Revision ID: 81c7c80e0f60
Revises: 002_biginteger_numeric_columns
Create Date: 2026-04-05 13:43:13.652164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81c7c80e0f60'
down_revision: Union[str, Sequence[str], None] = '002_biginteger_numeric_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_key')
    )

    # Insert an initial default project and admin key
    import hashlib
    import secrets
    import os
    
    # Generate a random 32-character hex key
    initial_key = secrets.token_hex(16)
    hashed_key = hashlib.sha256(initial_key.encode()).hexdigest()
    
    # Insert project
    op.execute("INSERT INTO projects (name, created_at) VALUES ('default', CURRENT_TIMESTAMP)")
    # Insert API Key (project 1 is the default since it's autoincrementing and the only row we inserted)
    op.execute(f"INSERT INTO api_keys (project_id, hashed_key, role, is_active, created_at) VALUES (1, '{hashed_key}', 'admin', true, CURRENT_TIMESTAMP)")
    
    # Print the key to the console so the user gets it during init/upgrade!
    print("\\n" + "="*60)
    print("🚀 OBSERVAKIT RBAC ENABLED")
    print(f"🔑 Your initial Admin API Key is: {initial_key}")
    print("Store this safely! It will not be shown again.")
    print("="*60 + "\\n")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    op.drop_table('projects')
    # ### end Alembic commands ###
